<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1 class="h2">Request log</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <!--
      <button class="btn btn-sm btn-outline-secondary">Share</button>
      <button class="btn btn-sm btn-outline-secondary">Export</button>
   -->
    </div>
  </div>
</div>

<div id="request-list" class="" style="height:600px"></div>


<div id="request-info-area" class="col-md-6 order-md-1" style="display:none">
  <form id="request-form">
      <div class="mb-3">
          <label for="person-id-number">Person ID-number</label>
          <input disabled="false" type="text" class="form-control" name="personal_id_number">
      </div>
      <!--
      <div class="mb-3">
          <label for="first_name">First name</label>
          <input type="text" class="form-control" name="first_name" >
      </div>

      <div class="mb-3">
          <label for="last_name">Last name</label>
          <input type="text" class="form-control" name="last_name">
      </div>

    <div class="mb-3">
        <label for="email">Email <span class="text-muted">(ofical email)</span></label>
        <input type="email" class="form-control" name="email" placeholder="you@example.com">
        <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
        </div>
    </div>

    <div class="col-md-6 mb-3">
        <label for="phone">Main phone</label>
        <input type="text" class="form-control" name="phone" placeholder="" value="">
    </div>
    <div class="col-md-6 mb-3">
        <label for="lastName">Secound phone</label>
        <input type="text" class="form-control" name="phone_2" placeholder="" value="">
    </div>

    <div class="mb-3">
        <label for="address">Address</label>
        <input type="text" class="form-control" name="address" placeholder="" required>
        <div class="invalid-feedback">
             Please enter a address
         </div>
    </div>

    <div class="mb-3">
        <label for="email_report">Email reports</label>
        <input type="email" class="form-control" name="email_report" placeholder="you@example.com">
        <div class="invalid-feedback">
            Please enter a valid email address.
        </div>
    </div>

    <div class="mb-3">
        <label for="email_report">Bank account</label>
        <input type="text" class="form-control" name="account">
    </div>

    <div class="mb-3">
        <label for="email_report">Website</label>
        <input type="text" class="form-control" name="website">
    </div>
    -->
    <button class="btn btn-primary btn-lg btn-block" type="submit">Save</button>
  </form>
</div>
