<?php
// site.config.inc: local

// Site
define ('SITE_URL', 'http://localhost:8070/');
define('KAPI_URL', 'http://localhost/kapi/');
define('BAPI_URL', 'http://localhost/bapi/');
define('CAPI_URL',  'http://localhost/capi/');
define ('INTERNAL_API', 'http://localhost/internal-api/');
define('API_URL',  'http://localhost/api/');
define('CURL',  'http://localhost/capi/');
define('INC_API',  'http://localhost/service2/json.php');

define('EVENTS_URL',  'http://localhost:8070/events/service/json.php');
define ('INVOICE_FOLDER', 'http://localhost:8070/finvoice/');
define('FIRST_INVOICE_FOLDER',  '/var/www/html/finvoice/');
define('ATTACHMENT_FOLDER', '/var/www/html/bilagor/');
define('CONTRACT_FOLDER',  '/var/www/html/kapi/avtal/');
define('LOGO_FOLDER',  '/var/www/html/logo/');

define('LOGIN_COOKIE', 'turtle-pay.dev');
// Debug
define('ERROR_REPORTING', true);