<!-- About -->
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1>
            Sportvärldens egen betaltjänst!
            </h1>
            <p>
           Turtle Pay har utvecklat en betaltjänst speciellt framtagen för att möta sportvärldens behov.
            </p>  
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin">
                
                <p class="p-color" style="max-width: 700px">
                Bland våra kunder märks idrottsklubbar inom t.ex. tennis, alpint, ridning, hockey och golf samt sportbutiker som tillhandahåller den bästa utrustningen till tusentals unga och vuxna sportutövare i Sverige.
                </p>
				
				<p class="p-color" style="max-width: 700px">
				Med Turtle Pay kan idrottsklubbar dramatiskt minska administrationen kring anmälning, betalning och påminnelse för alla typer av aktiviteter, inklusive medlems- och träningsavgifter. Samtidigt stärker vi klubbens likviditet och ger medlemmarna möjlighet att delbetala.
				</p>
				
				<?php /*
                <p class="p-color" style="max-width: 700px">
                För idrottsklubbar kapar vårt system dramatiskt administrationen kring anmälning, betalning och påminnelse av alla typer av aktiviteter, medlems- och träningsavgifter samtidigt som vi stärker klubbens likviditet. Klubbens medlemmar ges också möjlighet att delbetala.
                */ ?>
				<p class="p-color" style="max-width: 700px">
                Vi erbjuder även sportbutiker ett effektivt säljstöd i form av enkla och flexibla finansieringslösningar för sportutövande kunder i både fysisk butik och webbshop.
                </p>
                <p class="p-color" style="max-width: 700px">
                Det krävs ingen teknisk integration för att komma igång med Turtle Pay och vårt system är kompatibelt med alla moderna sport- och ekonomisystem på marknaden.
                </p>
                <p class="p-color" style="max-width: 700px">
                Vi tar ut endast ut en transaktionsavgift (2%). Inga andra kostnader och ingen bindningstid.
                </p>
                <p class="p-color" style="max-width: 700px">
                Turtle Pay är också en aktiv sponsor till många idrottsklubbar. Hör gärna av dig så berättar vi mer om vårt sponsorprogram.
                </p>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="image-phone">
                    <img src="images/turtle-pay-mobile.png" style="margin-left: auto; margin-right:auto;width:100%!important; max-width:280px!important; padding: 0 10px">
                </div>
            </div>
        </div

        <div class="columns" style="margin-top:0">
            <div class="column mobile-margin" style="padding-bottom: 40px">

                <div style="width: 100% padding:10px 20px">
                    <div style="background-color: #eafeea; border: 1px solid #cccccc; border-radius:8px; padding: 14px; width:100% ">
						<p style="font-style:italic; font-size: 14px">
							Turtle Pay är ett helägt dotterbolag till Memes Capital Partners som även grundade <a href="https://www.mfex.com" target="_blank"> MFEX (Mutual Funds Exchange)</a>, en av världens största marknadsplatser för fonder med 320 miljarder Euro i förvaltat kapital och som idag tillhör Euroclear Group.
                        </p>
                        <p style="font-style:italic; font-size: 14px; padding-top: 8px">
							Turtle Pay AB (org.nr. 559101-6786) är ett svenskt konsumentkreditinstitut under Finansinspektionens tillsyn sedan juni 2018.
                        </p>
					
                        <p style="font-style:italic; font-size: 14px">
						<?php /*
                        Turtle Pay är ett helägt dotterbolag till Memes Capital Partners som även grundade <a href="https://www.mfex.com" target="_blank"> MFEX (Mutual Funds Exchange)</a>, Europas största oberoende marknadsplats för fonder med över 194 miljarder Euro i förvaltat kapital, ett företag många i Sverige känner till som <a href="https://fondmarknaden.se" target="_blank">FONDMARKNADEN</a>. 
                        </p>
                        <p style="font-style:italic; font-size: 14px; padding-top: 8px">
                            Turtle Pay AB (org.nr. 559101-6786) är ett svenskt konsumentkreditinstitut under Finansinspektionens tillsyn sedan juni 2018.
                        </p>
						*/ ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
