
<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1>
                Välkommen till Turtle Pay!
            </h1>
            <?php /*
            <p style="font-size:18px; font-style:italic; color: #ffffff">
                -UPPDATERING PÅGÅR –<br>
                Just nu pågår uppdateringar av vårt system, vilket kan innebära vissa störningar i tjänsten.<br>
                Vi ber om överseende med detta och hänvisar till vår support för ytterligare information.<br>
                Tel 08-806220, info@turtle-pay.com<br>
                
            </p>
          
            <h2>Med Turtle Pay kan du erbjuda dina kunder köp på faktura eller delbetalning med ett enkelt knapptryck.</h2>
            <p style="font-size:16px">Ange dina företagsuppgifter nedan och hämta Turtle Pay-appen från AppStore.</p>
            <p style="font-size:16px">Kom igång inom 3 timmar under kontorstid.</p>
            <p style="font-size:14px; font-style:italic">Endast 2 % i transaktionsavgift. Inga övriga kostnader och inga bindningstider.</p>
			
			  */ ?>
			
			 <p style="font-size:16px;">Turtle Pay erbjuder idrottsklubbar och sportbutiker marknadens mest konkurrenskraftiga betaltjänst.</hp>
            <p style="font-size:16px; max-width: 700px">Minskad administration och ökad likviditet hos klubbarna samt effektivt säljstöd i butik frigör resurser för mer träning och bättre utrustning till Sveriges aktiva unga och vuxna sportutövare.</p>
            <p style="font-size:16px; max-width: 700px">Ange dina kontaktuppgifter för mer information, så hör vi av oss.</p>
            <br>
        </div>
    </div>
</section>

<section class="section bg" style="padding-bottom: 80px"> <?php /* background-color: #5a7d22; */ ?>
    <div class="container">  <?php /* background-color: #5a7d22; */ ?>
        
        <div class="columns">
            <div class="column">

				<div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <div class="control">
                                <h3 class="title is-4" style="color: #fff;">Kontakta mig!</h3>
                            </div>
                        </div>
                    </div>
                </div>
			
                <div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <!-- <label class="label">Organisationsnummer</label> -->
                            <div class="control">
                                <input id="orgno" class="orgno input" type="text" placeholder="Organisationsnummer">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <!--  <label class="label">Företag</label> -->
                           <div class="control">
                                <input id="company" class="input name" type="text" placeholder="Företagsnamn">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <!--  <label class="label">Kontakt</label>  -->
                            <div class="control">
                                <input id="contact" class="input name" type="text" placeholder="Kontaktperson" >
                            </div>
                        </div>
                    </div>
                </div>

                <div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <!-- <label class="label">E-post</label> -->
                            <div class="control">
                                <input id="email" class="input email" type="email" placeholder="E-post" value="">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="columns" style="margin-bottom: 0">
                    <div class="column mobile-margin">
                        <div class="field">
                            <!--  <label class="label">Telefon</label>  -->
                            <div class="control">
                                <input id="mobile" class="input mobile" type="text" placeholder="Telefon">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="columns">
                    <div class="column mobile-margin is-clearfix">
                        <div class="field is-pulled-left">
                            <div class="control" style="margin-top: 1px;">
                                <button id="eSendContact" class="button is-white " style="width:138px">
                                <span class="icon">
                                    <i class="fas fa-envelope"></i>
                                </span>
                                <span>Skicka</span></button>
                            </div>
                        </div>

                        <?php /*
                        <div class="is-pulled-left" style="margin-top: -8px">
                            <a  href="https://itunes.apple.com/SE/app/id1442085569?mt=8" target ="_blanK">
                                <img src="images/appstore-w.png" style="width:100%!important; width:144px!important;">
                            </a>
                        </div>
                        */ ?>

                    </div>
                </div>
            </div>
            <?php /*
            <div class="column appstore">
                <div class="image-phone">
                    <a href="https://itunes.apple.com/SE/app/id1442085569?mt=8" target ="_blanK">
                        <img src="images/appstore-w.png" style="margin-left: auto; margin-right:auto;width:100%!important; width:220px!important; padding: 0 10px">
                    </a>
                </div>
            </div>
             */
            ?>
        </div>
    </div>

</section>
