<?php

    if ($Current->isMobile == 'yes') {
        echo '<section class="section" style="padding-bottom:0px">';
        echo '<div class="container">';
    }
    else {
        echo '<section class="section">';
        echo '<div class="container">';
}
?>
<div class="columns margin-bottom">
    <div class="column">
        <div class="p-default" id="payment-status-text" style="padding-top:10px;">
    </div>
</div>
