version: '3.2'

services:
    db:
      image: mysql:5.7
      container_name: TPDbDev
      restart: always
      ports:
       - '3370:3306'
      environment:
        MYSQL_USER: admin
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./db:/var/lib/mysql
    php:
      depends_on:
       - db
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8070:80
      environment:
        PMA_HOST: db
      volumes:
        - ./html:/var/www/html/
    app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: TPAdminDev
      restart: always
      ports:
       - '8071:80'
      environment:
        PMA_HOST: db
volumes:
    db: