<?php

$Message['more-info'] = 'För information kontakta Turtle Pay AB på info@turtle-pay.com eller tel. 08-806220.';
$Message['exist'] = 'EN FAKTURA MED SAMMA BELOPP OCH REFERNS FINNS REDAN!';
$Message['no-valid-parameter'] = 'FELAKTIGT LÄNK!';

$Message['denied'] = 'MEDGES EJ!';
//
// Message for the progress
//
$Message['progress-mobile'] = '<strong>VAR GOD VÄNTA! </strong> <br/>';
$Message['progress-mobile'] .= 'Fakturan skickas nu till angiven e-postadress.</br>';
$Message['progress-mobile'] .= '<i>Lämna inte denna sida medan fakturan skickas.';        
$Message['progress-computer'] = '<strong>ÖPPNA DITT BANKID OCH SIGNERA!</strong> <br/>';


?>