<div class="modal" id="bankid-box">
    <div class="modal-background"></div>
    <div class="modal-card pl0 pr0  modal-width" style="margin-top: -150px!important; background-color:#183E4F">
        <header class="modal-card-head">
            <p class="modal-card-title has-text-centered">Signering</p>
        </header>
        <section class="modal-card-body">
            <p id="bankid-box-text" class="has-text-centered"></p>
        </section>
        <footer class="modal-card-foot">
            <button id="eBankIdBoxContinue" class="button is-dark w120 image-center" >Fortsätt</button>
        </footer>
    </div>
</div>