<div class="modal" id="message-box">
    <div class="modal-background"></div>
    <div class="modal-card pl0 pr0">
        <header class="modal-card-head">
            <p class="modal-card-title has-text-centered">Meddelande</p>
        </header>
        <section class="modal-card-body">
            <p id="message-box-text" class="has-text-centered"></p>
        </section>
        <footer class="modal-card-foot">
            <div class="has-text-centered w100p">
                <button id="eMessageBoxClose" onclick="View.removeClass('message-box','is-active');" class="button is-dark w120">OK</button>
            </div>
        </footer>
    </div>
</div>