<?php
// site.config.inc: test

// Site
define ('SITE_URL', 'http://turtle-pay.test/');
define('KAPI_URL', 'http://turtle-pay.test/kapi/');
define('BAPI_URL', 'http://turtle-pay.test/bapi/');
define('CAPI_URL',  'http://turtle-pay.test/capi/');
define('API_URL', 'http://turtle-pay.test/api/');
define('CURL', 'http://turtle-pay.test/capi/');
define('INC_API',  'http://turtle-pay.test/service2/json.php');

define('EVENTS_URL',  'http://turtle-pay.test/events/service/json.php');
define ('INVOICE_FOLDER', 'http://turtle-pay.test/finvoice/');
define('FIRST_INVOICE_FOLDER',  '../finvoice/');
define('ATTACHMENT_FOLDER', '../bilagor/');
define('LOGO_FOLDER',  '/Users/bogrusell/WebSites/turtle-pay.test/logo/');

define('LOGIN_COOKIE', 'turtle-pay.test');
// Debug
define('ERROR_REPORTING', true);