
<div id="uc-simulate" class="uc-section">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="title is-4 has-text-centered no-bottom" id="header-people-name">UC - Simulering</h1>

        <div class="columns">
            <div class="column">
                <p>People</p>
                <select id="eUcPeople" style="width:200px">
                    <option value="1">Test</option>
                  

                </select>
            </div>
           
            <div class="column">
                <div class="buttons">
                    <button class="button is-primary" id="eReportRaw">Report Raw</button>
                    <!-- <button class="button is-info" id="eReportFilter">Report Filter</button> -->
                    <button class="button is-dark" id="eCheck">Check</button>
                </div>
            </div>
            
            </div>
    </div>
    <div class="columns" style="padding-top: 12px;">
        <div id="uc-simulate-list" class="column" style="height:600px;"></div>
        <div id="uc-simulate-result" class="column" style="height:600px;">Test</div>
    </div>
</div>
