
<section class="hero is-light">
    <div class="hero-body">
        <div class="container">
            <h1>
            VANLIGA FRÅGOR & SVAR
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin" style="padding-bottom: 40px">
                
                <p class="p-header">Hur gör jag fakturaköp med Turtle Pay?</p>
                <p class="p-color">
                Enkelt! Tryck bara på ”Fakturaköp” i Turtle-appen och be kunden signera med sitt BankID.
                </p>

                <p class="p-header">Hur slår jag in fakturaköp i min kassa?</p>
                <p class="p-color">Du gör precis som vanligt i kassan när du registrerar ett fakturaköp.</p>

                <p class="p-color">Många butiker väljer att registrera fakturaköpet som kontant eftersom pengarna kommer direkt in på ert bankkonto från Turtle. Det kan dock vara bra att lägga upp en Turtle-knapp i kassan som alla fakturaköp och returer registreras på.</p>
                <p class="p-header">Hur returnerar jag ett fakturaköp?</p>
                <p class="p-color">Enkelt! Du gör precis som vanligt i kassan även när du returnerar ett fakturaköp.</p>
                <p class="p-color">I Turtle-appen trycker du sedan på ”Retur”, söker fram fakturaköpet i listan och ber kunden signera med sitt BankID.</p>
                <p class="p-color">Inget annat kreditinstitut har så enkel returfunktion som Turtle. Det gör att butiken har full kontroll på hela köpprocessen och slipper tidsödande och kostsamt krångel för kunden.</p>

                <p class="p-header">Vad händer om jag glömmer att returnera fakturaköpet i Turtle-appen?
                <p class="p-color">Ingenting händer om ni t.ex. betalar tillbaka returbeloppet direkt till kunden. Det är upp till butiken och er kund att bestämma hur ni vill göra. Det kan aldrig bli fel så länge ni följer era vanliga kvittorutiner som gäller vid returer.</p>

                <p class="p-header">Hur väljer kunden att delbetala ett köp?</p>
                <p class="p-color">Kunden väljer delbetalning först när fakturan ska betalas. Då finns möjligheten att betala valfritt belopp, dock med ett lägstabelopp över t.ex. 12, 24 eller 36 månader. Lägstabeloppet som ska betalas varje månad visas i appen när du gör en fakturaförfrågan och även i kundens BankID vid signering.</p>

                <p class="p-header">Hur stämmer man av butikens dagskassa?</p>

                <p class="p-color">Tryck bara på ”Dagskassa” i Turtle-appens meny så skickas dagens fakturaköp och returer till din e-postadress. Där kan du se hur mycket pengar butiken får från Turtle varje dag.</p>
                <p class="p-color">Dagligen skickas normal även en utbetalningsavi till butikens ekonomifunktion via e-post för bokföring och avstämning.</p>
                <p class="p-color">När får butiken pengarna vid fakturaköp?</p>
                <p class="p-color">Turtle betalar ut dagskassan till butikens bankgirokonto varje dag. Dagligen skickas normalt även en utbetalningsavi till butikens ekonomifunktion via e-post för bokföring och avstämning.</p>

                <p class="p-header">Vilka kreditvillkor gäller för kunden hos Turtle Pay?</p>
                <p class="p-color">Turtle konkurrerar med den i särklass bästa betallösning för fakturaköp i fysisk butik. Vi erbjuder villkor som skräddarsys efter butikens behov att tillhandahålla en attraktiv och problemfri betalningslösning för sina kunder. Därmed får de stora och ofta stelbenta kreditinstituten på marknaden efterlängtad konkurrens.</p>

                <p class="p-header">Hur får jag Turtle-appen om jag är butiksägare eller firmatecknare?</p>
                <p class="p-color">Gå till startsidan på www.turtle-pay.com. Där anger du dina företagsuppgifter och laddar sedan ned Turtle-appen från App Store. Du får ett mejl inom 3 timmar när ditt företag är aktiverat då är Turtle-appen klar att använda. Har du butikspersonal ber du dem ladda ned Turtle-appen och aktiverar dem i menyn under ”Företagssidor” genom att ange deras personnummer.</p>

                <p class="p-header">Vad är Turtle Pay?</p>
                <p class="p-color">Turtle Pay är ett svenskt konsumentkreditinstitut under Finansinspektionens tillsyn sedan juni 2018. Vi erbjuder konsumentkrediter i samarbete med butiker och tjänsteföretag i Sverige.</p>

                <p class="p-header">Vem står bakom Turtle Pay?</p>
                <p class="p-color">Turtle Pay är ett helägt dotterbolag till Memes Capital Partners som även grundade MFEX (Mutual Funds Exchange), Europas största oberoende marknadsplats för fonder, ett företag många i Sverige känner till som Fondmarknaden.se.</p>

                <p class="p-header">Övriga frågor</p>

                <p class="p-color">Vid övriga frågor kontakta gärna Turtle Pays kundtjänst på info@turtle-pay.com eller telefon 08-80 62 20.</p>



            </div>
        </div>

       
    </div>
</section>
