<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="">
            <img src="images/TurtlePay.png" width="90" height="46">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbar" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="people">
                People
            </a>
            <a class="navbar-item" href="company">
                Companies
            </a>
            <a class="navbar-item" href="invoice">
                Invoices
            </a>
            <a class="navbar-item" href="credit">
                Credit
            </a>
            <a class="navbar-item" href="bond">
                Bond
            </a>
            <a class="navbar-item" href="payment">
                Payment
            </a>
            <a class="navbar-item" href="reporting">
                Reporting
            </a>
            <a class="navbar-item" href="settings">
                Settings
            </a>
            <a class="navbar-item" href="request">
                Request
            </a>
            <a class="navbar-item" href="invoice-service">
                Service
            </a>
            <a class="navbar-item" href="tool">
                Tools
            </a>
            <a class="navbar-item" href="settlement">
                Settlement
            </a>
            <?php /*
            <a class="navbar-item" href="controlreporting">
                Control Reports
            </a>
            */ ?>
            <a class="navbar-item" href="logout">
               Logout
            </a>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <!--
                    <a class="button is-primary">
                        <strong>Sign up</strong>
                    </a>
                    -->
                    <a class="button is-light" id="eNavBarBack" style="display:none">
                        Back
                    </a>

                </div>
            </div>
        </div>
    </div>
</nav>
