<section class="hero is-primary">
    <div class="hero-body" style ="padding-bottom: 0; padding-top: 0;margin-bottom: 0;margin-top: 0;">
        <div class="container">
            <h1 style="padding-top: 10px;">
           Fakturor
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:0px; padding:0 0 0 0;">
            <div id="invoices-user-list" class="column">
            </div>
        </div>

    </div>
</section>
