<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:4px">

            <div class="column is-one-fifth is-horizontal-center">
                <div style="text-align: center; ">
                    <img src="images/turtle-pay-mobile.png" style="margin-left: auto; margin-right:auto;width:100%!important; max-width:280px!important; padding: 0 10px">
                </div>
            </div>

            <div class="column" style="margin-top:8px">
                <h1 class="title is-3">Välkommen till Turtle Pay.</h1>
                <h2 class="subtitle is-5">Vi erbjuder konsumentkrediter i samarbete med butiker och tjänsteföretag i Sverige.</h2>
            </div>
        </div>

        <div class="columns reverse" style="margin-top:12px">

            <div class="column is-one-fifth" style="margin-top:8px">
                <div style="text-align: center; ">
                    <img src="images/arrow.png" style="width:100%!important; max-width:80px!important; padding: 0 10px">
                </div>
            </div>

            <div class="column">
                <ul style="margin-left:20px">
                    <li >
                        Registrera ditt företag nedan och hämta Turtle Pay-appen från App Store.
                    </li>
                    <li>
                        Allt allt klart inom 1 timme*.
                    </li>
                    <li>
                        Endast 2 % i transaktionsavgift. Inga installations-, uppläggnings- eller abonnemangskostnader och inga bindningstider.
                    </li>
                </ul>
            </div>
        </div>

        <div class="columns">
              <div class="column is-one-fifth" style="padding-top:0; padding-bottom: 0">
              </div>
              <div class="column">
                  <div class="field">
                      <!-- <label class="label">Organisationsnummer</label> -->
                      <div class="control">
                          <input id="orgno" class="input orgno" type="text" placeholder="Org.nr.">
                      </div>
                  </div>
              </div>
          </div>

        <div class="columns">
            <div class="column is-one-fifth" style="padding-top:0; padding-bottom: 0">
            </div>
            <div class="column">
                <div class="field">
                    <!--  <label class="label">Företag</label> -->
                    <div class="control">
                        <input id="company" class="input name" type="text" placeholder="Företagetsnamn">
                    </div>
                </div>
            </div>
        </div>

        <div class="columns">
              <div class="column is-one-fifth" style="padding-top:0; padding-bottom: 0">
              </div>
                <div class="column">
                    <div class="field">
                        <!--  <label class="label">Kontakt</label>  -->
                        <div class="control">
                            <input id="contact" class="input name" type="text" placeholder="Kontaktperson" >
                        </div>
                    </div>
                </div>
            </div>

        <div class="columns">
              <div class="column is-one-fifth" style="padding-top:0; padding-bottom: 0">
              </div>
                <div class="column">
                    <div class="field">
                       <!-- <label class="label">E-post</label> -->
                        <div class="control has-icons-left">
                            <input id="contact-email" class="input email" type="email" placeholder="E-post" value="">
                            <span class="icon is-small is-left">
                                <i class="fas fa-envelope"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        <div class="columns">
              <div class="column is-one-fifth" style="padding-top:0; padding-bottom: 0">
              </div>
                <div class="column">
                    <div class="field">
                       <!--  <label class="label">Telefon</label>  -->
                        <div class="control">
                            <input id="contact-mobile" class="input mobile" type="text" placeholder="Telefon">
                        </div>
                    </div>
                </div>
            </div>

        <div class="columns">
              <div class="column is-one-fifth  style="padding-top:0; padding-bottom: 0">
              </div>
                <div class="column">
                    <div class="field is-grouped has-text-centered">
                        <div class="control">
                            <button id="send-contact" class="button is-info is-pulled-right" style<"margin-left:2+px">
                                <span class="icon">
                                    <i class="fas fa-envelope"></i>
                                </span>
                                <span>Skicka</span></button>
                        </div>
                    </div>
                </div>
            </div>

    </div>

</section>
