<section class="hero is-dark">
    <div class="hero-body">
        <div class="container">
            <h1>
           Kontakt
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin">
                <p class="p-color" style="margin-bottom: 2px;">
                Turtle Pay AB
                </p>
                <p class="p-color" style="margin-bottom: 2px;">
                P.O. Box 24078
                </p>
                <p class="p-color" style="margin-bottom: 2px;">
                SE-104 50 Stockholm
                 </p>
                <p class="p-color" style="margin-bottom: 2px;">
                Tel 08-806220
                </p>
                <p class="p-color" style="margin-bottom: 2px;">
                info@turtle-pay.com
                </p>

            </div>
        </div>

        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin">
                <p class="p-color" style="margin-bottom: 2px;">
                ÖPPETTIDER
                </p>

                <p class="p-color" style="margin-bottom: 2px;">
                Helgfri vardag 9-18
                </p>
                
                <p class="p-color" style="margin-bottom: 2px;">
                Helger 11-16
                </p>
            </div>
        </div>
        
        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin">
                <p style="font-style:italic; font-size: 16px; font-weight: bold">
                Klagomål
                </p>
                <p style="font-style:italic; font-size: 16px;">
                Vid klagomål kan du vända dig till Turtle Pays kundtjänst på telefon 08-806220 eller info@turtle-pay.com.
                </p>
                <p style="font-style:italic; font-size: 16px;">
                Om du fortfarande inte tycker att du fått rätt i en fråga kan du vända dig till Allmänna reklamationsnämnden, Konsumenternas Bank- och finansbyrå, Konsumenternas Försäkringsbyrå samt genom den kommunala konsumentvägledningen.
                </p>
            </div>
        </div>
    </div>
</section>