<?php
// site.config.inc: local

// Site
define ('SITE_URL', 'https://turtle-pay.com/events/');
define('KAPI_URL', 'http://localhost/kapi/');
define('BAPI_URL', 'http://localhost/bapi/');
define('CURL',  'http://localhost/capi/');
define ('INVOICE_FOLDER', 'https://turtle-pay.com/finvoice/');
define('FIRST_INVOICE_FOLDER',  '/var/www/html/finvoice/');
define('LOGO_FOLDER',  '/var/www/html/logo/');

define('LOGIN_COOKIE', 'www.turtle-pay.com');

// Debug
define('ERROR_REPORTING', false);