
<section class="hero is-light">
    <div class="hero-body">
        <div class="container">
            <h1>
            Integritetspolicy
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="columns" style="margin-top:4px">
            <div class="column mobile-margin">
                <p class="p-color">
                Skyddet av ditt privatliv är väldigt viktigt för Turtle Pay. Därför behandlar vi dina personuppgifter på ett ansvarsfullt och säkert sätt. 
                </p>
                <p class="p-color">
                Genom att klicka här hittar du information om hur vi samlar in, använder och sparar dina personuppgifter samt vilka rättigheter du har.
                </p>
                <p class="p-color">
                <a href="https://turtle-pay.com/integritetspolicy/" target="_blank">Visa integritetspolicy</a>
                </p>
            </div>
        </div>

       
    </div>
</section>
