<!-- Services -->
<section class="section" id="services">
  <div class="section-heading">
    <h3 class="title is-2">Uppehållstillstånd</h3>
    <h4 class="subtitle is-5">Migrationsexperten kan hälpa er med uppehållstillstånd, för att flytta till någon i Sverige</h4>
  </div>
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="box">
          <div class="content">
            <h4 class="title is-5">Vi hjälper hon/han under hela processen från ansökan till färdigt beslut.</h4>
          För att flytta till din familj eller anhörige i Sverige behöver du ett uppehållstillstånd. Här kan du läsa
          om hur vi på Migrationsspecialisten kan hjälpa er med din ansökan och med eventuella barn., med er ansökan
           så den korrekt från första stund.
          </div>
        </div>
      </div>
      <div class="column">
        <div class="box">
          <div class="content">
            <h4 class="title is-5">Uppehållstillstånd för att flytta till Din make, maka, registrerad partner eller sambo i Sverige. </h4>
            Om du är medborgare i ett land utanför EU och vill flytta till en familjemedlem i Sverige behöver du uppehållstillstånd. Du kan få
            uppehållstillstånd om du är gift, har ingått partnerskap eller är sambo med någon i Sverige. Familjemedlemmen i Sverige måste vara
            svensk medborgare eller ha permanent uppehållstillstånd.
          </div>
        </div>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <div class="box">
          <div class="content">
            <h4 class="title is-5">Makar, registrerade partners eller sambor.</h4>
            Du har rätt att få uppehållstillstånd om du är gift, har ingått registrerat partnerskap eller
            är sambo med någon som bor i Sverige. Din partner bör registrera ert äktenskap eller partnerskap hos S
            katteverket i Sverige. Med sambo menas ett par som inte är gifta men som bor och lever tillsammans som i
            ett äktenskap. Att ni har levt tillsammans under till exempel ett turistbesök räcker inte
          </div>
        </div>
      </div>
      <div class="column">
        <div class="box">
          <div class="content">
            <h4 class="title is-5">Rådgivning och strategier</h4>
            Vi kan även bistå med råd och strategier för att smidgast lyckas få ett uppehållstilstånd.
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="section-heading" style="padding-top: 24px">
    <h3 class="title is-2">Asyl och Skydd</h3>
    <h4 class="subtitle is-5">(Text)</h4>
  </div>
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="box">
          <div class="content">
            <h4 class="title is-5">(Rubrik)</h4>
         (text)
          </div>
        </div>
      </div>
      <div class="column">
        <div class="box">
          <div class="content">
              <h4 class="title is-5">(Rubrik)</h4>
              (text)
          </div>
        </div>
      </div>
    </div>
</section>
